[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["sync", "macros", "rt"] }
async-trait = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
flate2 = "1.1.9"
tar = "0.4.46"
shlex = "2.0.1"
log = { workspace = true }
