[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "glow"] }
egui = { version = "0.36.1", default-features = false, features = ["default_fonts"]}
sqlx = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
chrono = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.35.0", features = ["x11", "wayland"] }

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-win = "5.4.1"
image = { version = "0.25.10", default-features = false, features = ["bmp"] }
